version: '3.3'

services:
  redis-master:
    build:
      context: .
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    ports:
          - 6379:6379
    logging:
      driver: json-file
    depends_on:
      - vault

  redis-slave:
    build:
      context: .
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    logging:
      driver: json-file
    depends_on:
      - vault

  redis-sentinel:
    build:
      context: .
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    logging:
      driver: json-file
    depends_on:
      - vault

  redis-sentinel2:
    build:
      context: .
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    logging:
      driver: json-file
    depends_on:
      - vault

  redis-sentinel3:
    build:
      context: .
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    logging:
      driver: json-file
    depends_on:
      - vault

  vault:
    image: ascent/ascent-vault
    hostname: vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_DEV_ROOT_TOKEN_ID=vaultroot
      - tls_disable=1
      - GIT_ACCESS_TOKEN=$GIT_ACCESS_TOKEN
    ports:
      - "8200:8200"
    command: server -dev
    networks:
      - ascentnet

networks:
 ascentnet:
    driver: bridge
